// vue/src/App.vue
<script setup lang="ts">
import KanbanCol from './components/KanbanCol.vue'
import KanbanInput from './components/KanbanInput.vue'
import KanbanItem from './components/KanbanItem.vue'
import { ref, computed } from 'vue'
import { Task } from './types'

const tasks = ref<Task[]>([]);

const backlogTasks = computed(() => tasks.value.filter(task => task.status === 'backlog'));
const todoTasks = computed(() => tasks.value.filter(task => task.status === 'todo'));
const inProgressTasks = computed(() => tasks.value.filter(task => task.status === 'in-progress'));
const reviewTasks = computed(() => tasks.value.filter(task => task.status === 'review'));
const doneTasks = computed(() => tasks.value.filter(task => task.status === 'done'));

const handleAddTask = (status: Task["status"], title: string, description: string) => {
  const newTask = {
    id: tasks.value.length + 1,
    title,
    description,
    status
  };
  tasks.value.push(newTask);
};

const handleDeleteTask = (id: string) => {
  tasks.value = tasks.value.filter(task => task.id !== id);
};
</script>

<template>
  <main className="min-h-screen bg-gray-100 p-4 overflow-x-auto">
    <h1 className="text-4xl text-center font-bold">Kanban Board</h1>
    <div className="flex gap-4 mt-4">
      <KanbanCol title="Backlog">
        <KanbanItem v-for="task in backlogTasks" :key="task.id" :task="task"
          @delete="handleDeleteTask" />
        <KanbanInput @add="({ title, description }) => handleAddTask('backlog', title, description)" />
      </KanbanCol>
      <KanbanCol title="To Do">
        <KanbanItem v-for="task in todoTasks" :key="task.id" :task="task"
          @delete="handleDeleteTask" />
        <KanbanInput @add="({ title, description }) => handleAddTask('todo', title, description)" />
      </KanbanCol>
      <KanbanCol title="In Progress">
        <KanbanItem v-for="task in inProgressTasks" :key="task.id" :task="task"
          @delete="handleDeleteTask" />
        <KanbanInput @add="({ title, description }) => handleAddTask('in-progress', title, description)" />
      </KanbanCol>
      <KanbanCol title="Review">
        <KanbanItem v-for="task in reviewTasks" :key="task.id" :task="task"
          @delete="handleDeleteTask" />
        <KanbanInput @add="({ title, description }) => handleAddTask('review', title, description)" />
      </KanbanCol>
      <KanbanCol title="Done">
        <KanbanItem v-for="task in doneTasks" :key="task.id" :task="task"
          @delete="handleDeleteTask" />
        <KanbanInput @add="({ title, description }) => handleAddTask('done', title, description)" />
      </KanbanCol>
    </div>
  </main>
</template>

// react/src/App.tsx
import KanbanCol from "./components/KanbanCol"
import KanbanInput from "./components/KanbanInput"
import { useState } from "react"
import { Task } from "./types"
import KanbanItem from "./components/KanbanItem"

function App() {
  const [tasks, setTasks] = useState<Task[]>([]);

  const handleAddTask = (status: Task['status'], title: string, description: string) => {
    const newTask: Task = {
      id: crypto.randomUUID(),
      title,
      description,
      status,
    }
    setTasks([...tasks, newTask])
  }

  const handleDeleteTask = (id: string) => {
    setTasks(tasks.filter(task => task.id !== id))
  }

  return (
    <main className="min-h-screen bg-gray-100 p-4 overflow-x-auto">
      <h1 className="text-4xl text-center font-bold">Kanban Board (React)</h1>
      <div className="flex gap-4 mt-4">
        <KanbanCol title="Backlog">
          {tasks.filter(task => task.status === 'backlog').map(task => (
            <KanbanItem key={task.id} {...task} onDelete={handleDeleteTask} />
          ))}
          <KanbanInput onAddTask={({ title, description }) => handleAddTask('backlog', title, description)} />
        </KanbanCol>
        <KanbanCol title="To Do">
          {tasks.filter(task => task.status === 'todo').map(task => (
            <KanbanItem key={task.id} {...task} onDelete={handleDeleteTask} />
          ))}
          <KanbanInput onAddTask={({ title, description }) => handleAddTask('todo', title, description)} />
        </KanbanCol>
        <KanbanCol title="In Progress">
          {tasks.filter(task => task.status === 'in-progress').map(task => (
            <KanbanItem key={task.id} {...task} onDelete={handleDeleteTask} />
          ))}
          <KanbanInput onAddTask={({ title, description }) => handleAddTask('in-progress', title, description)} />
        </KanbanCol>
        <KanbanCol title="Review">
          {tasks.filter(task => task.status === 'review').map(task => (
            <KanbanItem key={task.id} {...task} onDelete={handleDeleteTask} />
          ))}
          <KanbanInput onAddTask={({ title, description }) => handleAddTask('review', title, description)} />
        </KanbanCol>
        <KanbanCol title="Done">
          {tasks.filter(task => task.status === 'done').map(task => (
            <KanbanItem key={task.id} {...task} onDelete={handleDeleteTask} />
          ))}
          <KanbanInput onAddTask={({ title, description }) => handleAddTask('done', title, description)} />
        </KanbanCol>
      </div>
    </main>
  )
}

export default App
