// vue/src/components/common/Button.vue
<template>
    <button
        :class="cn('transition-all text-white px-4 py-2 rounded focus:ring-4 cursor-pointer', variantClass)"
    >
        <slot></slot>
    </button>
</template>

<script setup lang="ts">
import { cn } from '../../lib/utils'

const props = defineProps<{
    variant: 'primary' | 'secondary' | 'destructive'
}>();

const { variant } = props;

const variantClass = variant === 'primary'
    ? 'bg-blue-500 hover:bg-blue-600 focus:ring-blue-400'
    : variant === 'secondary'
    ? 'bg-gray-500 hover:bg-gray-600 focus:ring-gray-400'
    : 'bg-red-500 hover:bg-red-600 focus:ring-red-400';
</script>

// react/src/components/common/Button.tsx
import { cn } from "../../lib/utils";

interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
    variant: 'primary' | 'secondary' | 'destructive';
}

const Button: React.FC<ButtonProps> = ({
    className = '',
    children,
    variant = 'primary',
    ...props
}) => {
    let variantClass = 'bg-blue-500 hover:bg-blue-600 ring-blue-400';

    if (variant === 'secondary') {
        variantClass = 'bg-gray-500 hover:bg-gray-600 ring-gray-400';
    } else if (variant === 'destructive') {
        variantClass = 'bg-red-500 hover:bg-red-600 ring-red-400';
    }

    return (
        <button
            className={cn('transition-all text-white px-4 py-2 rounded focus:ring-4 cursor-pointer', variantClass, className)}
            {...props}
        >
            {children}
        </button>
    );
};

export default Button;
