// vue/src/components/common/Textarea.vue
<template>
    <textarea
        class="rounded-md border border-slate-300 bg-transparent transition-shadow px-3 py-2 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-neutral-300 disabled:cursor-not-allowed disabled:opacity-50"
        v-model="modelValue"
    />
</template>

<script setup lang="ts">
const modelValue = defineModel({
    type: String,
    default: ''
});
</script>

// react/src/components/common/Textarea.tsx
import { cn } from "../../lib/utils"

export default function Textarea({
  className,
  ...props
}: React.TextareaHTMLAttributes<HTMLTextAreaElement> & {
  className?: string
}) {
  return (
    <textarea
      className={cn(
        "w-full rounded-md border border-slate-300 bg-transparent transition-shadow px-3 py-2 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-neutral-300 disabled:cursor-not-allowed disabled:opacity-50",
        className
      )}
      {...props}
    />
  )
}
